### ISSUE TITLE
Times where it doesn't update

### ISSUE THREAD

**Issue by Foxandxss** [wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration#1] opened 2019-09-18 08:24 UTC
Hello my friend.

My GF with an active 1 + samsung A7 (same kind of solution as yours but without autonotification) and myself with an active 2 + note 10+.

We have the same problem, there are times where it doesn't update. In my case it is stuck at 18:52 from yesterday (now it is 10:23 here). I can restart the phone or the clock and it doesn't update.

My GF has the same issue.

If I go to watchmaker, I can see the face but it has the same value so I think it is not an issue with watchmaker itself. Not sure if I can evaluate the variables at tasker to see what it gets.

If I can't fix this, I would need to create my own widget or something with IoB and other interesting stuff.

Cheers mate.

**Comment by FreDiabetics** [comment] 2019-09-18 15:00
sorry :D for that closing mistake.....

so, have you given every single permission thats needed for Tasker, AutoNotification, Galaxy Wearable, xDrip+ and Watchmaker? and dont forget to deactivate the battery optimizing. I have made a little pictured Guide of what to do. I´m using a Samsung Galaxy A70 with Android 9 Pie, it may look different to your´s if you´re using a different Smartphone then Samsung. But I think you get what I want to show you.

![1](https://user-images.githubusercontent.com/45721291/65160252-b2d5f900-da35-11e9-9d23-475054811cdf.jpg)
![2](https://user-images.githubusercontent.com/45721291/65160253-b2d5f900-da35-11e9-94a6-6bf9eb63bdfe.jpg)
![3](https://user-images.githubusercontent.com/45721291/65160254-b36e8f80-da35-11e9-8f21-6078a128371a.jpg)
![4](https://user-images.githubusercontent.com/45721291/65160256-b36e8f80-da35-11e9-8115-4f951584da65.jpg)
![5](https://user-images.githubusercontent.com/45721291/65160257-b36e8f80-da35-11e9-9f14-f612587b6b14.jpg)
![6](https://user-images.githubusercontent.com/45721291/65160259-b4072600-da35-11e9-9d3f-ae200158cfdf.jpg)
![7 (1)](https://user-images.githubusercontent.com/45721291/65160260-b4072600-da35-11e9-9779-611ff87b532c.jpg)
![7 (2)](https://user-images.githubusercontent.com/45721291/65160262-b4072600-da35-11e9-8adb-58485ce3886c.jpg)
![8](https://user-images.githubusercontent.com/45721291/65160263-b4072600-da35-11e9-891b-d6067c858c5a.jpg)
![9](https://user-images.githubusercontent.com/45721291/65160264-b49fbc80-da35-11e9-8ebd-b6b0469f07d8.jpg)
![10](https://user-images.githubusercontent.com/45721291/65160266-b49fbc80-da35-11e9-9d3d-5e6096c9bf2f.jpg)
![11](https://user-images.githubusercontent.com/45721291/65160268-b49fbc80-da35-11e9-89bd-38e5e8c1153c.jpg)
![12](https://user-images.githubusercontent.com/45721291/65160269-b49fbc80-da35-11e9-9ee9-f72633cc7b5e.jpg)
![13](https://user-images.githubusercontent.com/45721291/65160271-b49fbc80-da35-11e9-91fe-53c36cdc37d5.jpg)
![14](https://user-images.githubusercontent.com/45721291/65160272-b49fbc80-da35-11e9-991e-6b51be0155a7.jpg)
![15](https://user-images.githubusercontent.com/45721291/65160273-b5385300-da35-11e9-9809-62c26ed4b7c3.jpg)
![17](https://user-images.githubusercontent.com/45721291/65160274-b5385300-da35-11e9-8711-61efff1871e5.jpg)
![18](https://user-images.githubusercontent.com/45721291/65160275-b5385300-da35-11e9-877b-6c7ec54271c1.jpg)
![19](https://user-images.githubusercontent.com/45721291/65160277-b5385300-da35-11e9-8145-4324b1a39dbd.jpg)
![20](https://user-images.githubusercontent.com/45721291/65160278-b5d0e980-da35-11e9-99d7-6bd93e94620e.jpg)
![21](https://user-images.githubusercontent.com/45721291/65160279-b5d0e980-da35-11e9-8784-2907609a02a0.jpg)
![22](https://user-images.githubusercontent.com/45721291/65160281-b5d0e980-da35-11e9-8438-e16c781c1e49.jpg)
![23](https://user-images.githubusercontent.com/45721291/65160282-b5d0e980-da35-11e9-987b-94f8827ac880.jpg)

**Comment by Foxandxss** [comment] 2019-09-18 15:16
Very helpful.

Now it is stuck with a %ansummarytext (using one of your watchfaces). I need to see why. Apparently {tbgtime} still works (and updated!) but shows in black (and not the nice colors you configured) and {tglucose} shows %antitle.

Maybe I should start over, the hard part was configuring the app to behave.

**Comment by FreDiabetics** [comment] 2019-09-18 15:20
And why don´t you use the Wearable Widgets App?

I can show you hpow to download the Wearable Widgets App to your Samsung Galaxy Active 1 and Samsung Galaxy Active 2.

You have to buy the Wearable Widgets App on the Galaxy Store. BUT you can´t do it with the Active or the Active 2, because Wearable Widgets don´t support them directly. But if you have bought it already you only have to go to your Galaxy Store then click on the Menü and navigate to Profile, the select All (there are all apps listed you ever bought or install on any Samsung device). Then scroll down till you see the Wearable Widgets App, click on it and download it to your watch...



the thing with %ansummarytext and %antitle ist the variable. as i wrote down, press the play button and 5 at least 5 minutes, you can open the Ryder VARS there you can look if your values shown already or if theyre not look on the screenshot below there you can see whats happening. press the play button and switch to this ryder, then wait 5 minutes until your Values appear ;)

**Comment by FreDiabetics** [comment] 2019-09-18 15:22
![Screenshot_20190918-171933_Tasker](https://user-images.githubusercontent.com/45721291/65162045-ee25f700-da38-11e9-85aa-f1ab2b719a1f.jpg)

**Comment by FreDiabetics** [comment] 2019-09-18 15:31
And last thing. I didn´t mentioned. You´re forced to use Autonotification, otherwise the Values can change there content. F. ex. if your plug in your chargingcabel you get a minimzed notification at the statusbar.  Sometimes your watch shows this notification instead of the BG-Value. If you´re using Autonotification your able to ignore all other notifications  except xDrip. without Autonotification it´s a 50/50 chance to get that issue.

**Comment by Foxandxss** [comment] 2019-09-18 15:34
Yes, I have seen that what you say with my GF. She sometimes had another message.

About my issue. I am a moron (sorry!) I had the autonotification trial and it lasted until the exact same minute it stopped sending me stuff. I paid for it (after I deleted all the tasker config) and recreted it. Now everything works like a charm.

Those images you put are very nice for the docs. 

Many thanks!!

PS: About the widget, I tried that in the past but I may create a widget myself that goes against nightscout so I can show not only BG but IoB, CoB, etc.

**Comment by wagnefrede** [comment] 2019-09-18 15:36
yes please doewnload AutoApps from the Play store, then open it and buy Autonotification. then you have to start over with setup them all. then you dont get that issues again. yesterday i set it up the same way on a smartphone from a facebook friend. she had the excat issue like you. she also didn´t bought the AutoNotification App at
 AutoApps

> Yes, I have seen that what you say with my GF. She sometimes had another message.
> 
> About my issue. I am a moron (sorry!) I had the autonotification trial and it lasted until the exact same minute it stopped sending me stuff. I paid for it (after I deleted all the tasker config) and recreted it. Now everything works like a charm.
> 
> Those images you put are very nice for the docs.
> 
> Many thanks!!
> 
> PS: About the widget, I tried that in the past but I may create a widget myself that goes against nightscout so I can show not only BG but IoB, CoB, etc.

yes please doewnload AutoApps from the Play store, then open it and buy Autonotification. then you have to start over with setup them all. then you dont get that issues again. yesterday i set it up the same way on a smartphone from a facebook friend. she had the excat issue like you. she also didn´t bought the AutoNotification App at
 AutoApps

**Comment by FreDiabetics** [comment] 2019-09-18 15:36
> Yes, I have seen that what you say with my GF. She sometimes had another message.
> 
> About my issue. I am a moron (sorry!) I had the autonotification trial and it lasted until the exact same minute it stopped sending me stuff. I paid for it (after I deleted all the tasker config) and recreted it. Now everything works like a charm.
> 
> Those images you put are very nice for the docs.
> 
> Many thanks!!
> 
> PS: About the widget, I tried that in the past but I may create a widget myself that goes against nightscout so I can show not only BG but IoB, CoB, etc.

yes please doewnload AutoApps from the Play store, then open it and buy Autonotification. then you have to start over with setup them all. then you dont get that issues again. yesterday i set it up the same way on a smartphone from a facebook friend. she had the excat issue like you. she also didn´t bought the AutoNotification App at
 AutoApps

**Comment by FreDiabetics** [comment] 2019-09-18 15:40
Cool :) have recieved you´re donation :) thank you my friend 👍 if you have any issues again. please feel free to PM me on every time 🥇

**Comment by Foxandxss** [comment] 2019-09-27 08:16
Have you seen the issue where phone is OK (tasker VARs updated and watchmaker preview is updated) but the watch is not. And sometimes if I click the "Copy to watch" button it says that the watch doesn't respond. Happens with note10+ / active 2 and a galaxy a7 + active 1.

I tried to find a battery save mode for the watch but I didn't find one.

**Comment by FreDiabetics** [comment] 2019-09-27 08:29
Thats the problem. The Galaxy Active 1 and 2 are not official supporting  Watchmaker and the other way around. The solution with downloading the apps from my account is only a little backdoor. I think Samsung could close that door at anytime in the future. 
I think it might be good to set the watch to Galaxy Watch active in Watchmaker. You know what I ?mean.

But you are not the first that got that issue. I installed that all to 4 Samsung Galaxy Active 2 with Samsung Galaxy so and xdrip+ and until today there was one single issue with connection. I think it could help to give all permissions and disable all battery optimizing for: AutoNotification, Watchmaker, Tasker, Galaxy Wearable, Galaxy Watch Active Plugin, Samsung Accessory Service and all other Apps which are involved in the connection to the Watch. 

Did you download the Watchmaker companion app only from my Account? 

I think it might help to delete the Watchmaker companion app on both Watches. And then buy it with your account. If you have downloaded it from my Account and delete the account after that, your smartphone gets an issue do connect to the watch because the owner of the app is somebody else. So delete the Watchmaker companion app and buy it again with your own account but buy it for you and then again for the second watch. So you buy it 2 Times. 

I can remember that this issue occured only one time and after I had done what I described above it works fine. So maybe that's the point. 

Let me know if you succeed 😉

**Comment by Foxandxss** [comment] 2019-09-27 08:35
The companion was downloaded directly from the galaxy store (and paid for it, both cases).

I didn't have watchmaker "off" from battery optimization. Let's see how it goes. Will do it on my GF setup as well, hers is way more fragile for some reason (I think it is because she leaves the watch somewhere and with all the disconnections, it doesn't update).

Ill update in a few days.

**Comment by Foxandxss** [comment] 2019-10-03 08:20
Still happens to both of us. It used to happen once per few days. Now a couple of times per day.

Right now it is 10:04 and was updated at 9:23. If I go to watchmaker it shows the correct input. Then I go to the watch and I switch from watch maker to another watchface, then back. Then I open watchmaker on the phone and I send the face again and it updates in a few minutes.

**Comment by FreDiabetics** [comment] 2019-10-03 22:17
did you activate High Priority Notification on xDrip settings?

and pls dont install the latest tasker update, because that causes many connection issues too. if you have done that you can use my troubleshooting PDF to get the previous version.

**Closed as completed** 2020-05-03 17:49 UTC

**Comment by FreDiabetics** [comment] 2020-05-03 17:51
Look in the wiki for the new instrcutions and Watchfaces ;) I close this at this point :) thanks for your support pm me of the issue is still there but the old Watchfaces shouldn't work anymore. I have given them them and I'll publish new redesigned versions but first I suit them to my new instrcutions keep watching  my watchmaker profile for for updates
